# Generated by Django 6.0.2 on 2026-02-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_email_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('xray', 'X-Ray'), ('ultrasound', 'Ultrasound'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('ecg', 'ECG'), ('urinalysis', 'Urinalysis'), ('covid', 'COVID-19 Test'), ('diabetes', 'Diabetes Test'), ('thyroid', 'Thyroid Test'), ('other', 'Other')], max_length=50)),
                ('test_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='patient.patient')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
